# Generated by Django 5.1.5 on 2025-01-29 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fahrenheit", models.IntegerField()),
                ("celsius", models.IntegerField()),
                ("time", models.TimeField(default=django.utils.timezone.now)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "temperature",
            },
        ),
    ]
