# Generated by Django 5.1.5 on 2025-04-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AviationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acceleration", models.DecimalField(decimal_places=2, max_digits=2)),
                ("altitude", models.IntegerField()),
                ("speed", models.DecimalField(decimal_places=2, max_digits=2)),
                ("latitude", models.DecimalField(decimal_places=2, max_digits=6)),
                ("longitude", models.DecimalField(decimal_places=2, max_digits=6)),
                ("distance_caution", models.BooleanField(null=True)),
                ("temperature", models.IntegerField()),
                ("nautical_miles", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "aviation_data",
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="aviation_da_timesta_0cfdee_idx"
                    )
                ],
            },
        ),
    ]
