# Generated by Django 5.1.5 on 2025-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviation_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aviationdata",
            name="distance_caution",
        ),
        migrations.RemoveField(
            model_name="aviationdata",
            name="nautical_miles",
        ),
        migrations.AddField(
            model_name="aviationdata",
            name="fuel",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="aviationdata",
            name="proximity_to_object_in_cm",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="aviationdata",
            name="speed",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="aviationdata",
            name="temperature",
            field=models.IntegerField(null=True),
        ),
    ]
