# Generated by Django 5.1.5 on 2025-04-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviation_data", "0002_remove_aviationdata_distance_caution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aviationdata",
            name="acceleration",
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="aviationdata",
            name="altitude",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="aviationdata",
            name="latitude",
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name="aviationdata",
            name="longitude",
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name="aviationdata",
            name="speed",
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
    ]
